
buildscript {
    repositories {
        google()
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.7.2'
    }
}

allprojects {
    repositories {
        google()
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven { url 'https://maven.google.com' }
        mavenCentral()
    }

    configurations.all {
        resolutionStrategy {
            // Force consistent slf4j version to avoid conflicts
            force 'org.slf4j:slf4j-api:1.7.36'
        }
    }
}

ext {
    reactNativeLibVersion = "0.83.0"
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

//task testClasses {}